config/routes.rb
ReportCenter::Application.routes.draw do

  get "home/index"
  root :to => "home#index"

  resources :activities

  resources :products do
    collection do
      get :search
    end
  end

  resources :orders

  resources :sales_channels do
    resources :sales_channel_apis
  end

  resources :sales_channel_apis

  resources :product_outer_mappings

  devise_for :users

end

app/models/sales_channel_api.rb
class SalesChannelApi < ActiveRecord::Base
  validates :name, :presence => true, :length => 2..255
  validates :app_key, :presence => true, :length => 2..255, :uniqueness => true
  validates :app_secret, :presence => true, :length => 2..255
  validates :session_key, :length => { :maximum => 255 }
  validates :url, :length => { :maximum => 255 }

  belongs_to :sales_channel
end

app/controllers/sales_channel_apis_controller.rb
class SalesChannelApisController < ApplicationController
  before_filter :authenticate_user!

  # GET /sales_channel_apis
  # GET /sales_channel_apis.json
  def index
    @sales_channel = SalesChannel.find(params[:sales_channel_id])
    @sales_channel_apis = @sales_channel.apis

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sales_channel_apis }
    end
  end

  # GET /sales_channel_apis/1
  # GET /sales_channel_apis/1.json
  def show
    @sales_channel_api = SalesChannelApi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @sales_channel_api }
    end
  end

  # GET /sales_channel_apis/new
  # GET /sales_channel_apis/new.json
  def new
    @sales_channel = SalesChannel.find(params[:sales_channel_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @sales_channel }
    end
  end

  # GET /sales_channel_apis/1/edit
  def edit
    @sales_channel_api = SalesChannelApi.find(params[:id])
  end

  # POST /sales_channel_apis
  # POST /sales_channel_apis.json
  def create
    @sales_channel = SalesChannel.find(params[:sales_channel_id])
    @sales_channel_api = SalesChannelApi.new(params[:sales_channel_api])
    @sales_channel_api.sales_channel = @sales_channel

    respond_to do |format|
      if @sales_channel_api.save
        format.html { redirect_to @sales_channel_api, :notice => 'Sales channel api was successfully created.' }
        format.json { render :json => @sales_channel_api, :status => :created, :location => @sales_channel_api }
      else
        format.html { render :action => "new" }
        format.json { render :json => @sales_channel_api.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sales_channel_apis/1
  # PUT /sales_channel_apis/1.json
  def update
    @sales_channel_api = SalesChannelApi.find(params[:id])

    respond_to do |format|
      if @sales_channel_api.update_attributes(params[:sales_channel_api])
        format.html { redirect_to @sales_channel_api, :notice => 'Sales channel api was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @sales_channel_api.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_channel_apis/1
  # DELETE /sales_channel_apis/1.json
  def destroy
    @sales_channel_api = SalesChannelApi.find(params[:id])
    @sales_channel_api.destroy

    respond_to do |format|
      format.html { redirect_to sales_channel_apis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sales_channel_apis_helper.rb
module SalesChannelApisHelper
end

app/views/sales_channel_apis/_form.html.erb
<% if @sales_channel_api.nil? %>
  <% @sales_channel_api = @sales_channel.apis.build %>
<% end %>
<%= form_for([@sales_channel, @sales_channel_api]) do |f| %>
  <% if @sales_channel_api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_channel_api.errors.count, "error") %> prohibited this sales_channel_api from being saved:</h2>

      <ul>
      <% @sales_channel_api.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :app_key %><br />
    <%= f.text_field :app_key %>
  </div>
  <div class="field">
    <%= f.label :app_secret %><br />
    <%= f.text_field :app_secret %>
  </div>
  <div class="field">
    <%= f.label :session_key %><br />
    <%= f.text_field :session_key %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :is_enable %><br />
    <%= f.check_box :is_enable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales_channel_apis/_widget_api_select.html.erb
<div class="api-select">
  <%=select_tag "sales_channel_id", options_from_collection_for_select(SalesChannel.all, "id", "name"), :prompt => "Select..." %>
  <%=form.select :sales_channel_api_id, [], :prompt => "Select sales channel..." %>
</div>
<script type="text/javascript">
  var sales_channel_apis_url = "<%= sales_channel_apis_path %>.json";
</script>

app/views/sales_channel_apis/edit.html.erb
<h1>Editing sales_channel_api</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_channel_api %> |
<%= link_to 'Back', sales_channel_sales_channel_apis_path(@sales_channel_api.sales_channel) %>

app/views/sales_channel_apis/index.html.erb
<h1>Listing sales_channel_apis</h1>

<table>
  <tr>
    <th>Name</th>
    <th>App key</th>
    <th>App secret</th>
    <th>Session key</th>
    <th>Url</th>
    <th>Is enable</th>
    <th>Sales channel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sales_channel_apis.each do |sales_channel_api| %>
  <tr>
    <td><%= sales_channel_api.name %></td>
    <td><%= sales_channel_api.app_key %></td>
    <td><%= sales_channel_api.app_secret %></td>
    <td><%= sales_channel_api.session_key %></td>
    <td><%= sales_channel_api.url %></td>
    <td><%= sales_channel_api.is_enable %></td>
    <td><%= sales_channel_api.sales_channel.name %></td>
    <td><%= link_to 'Show', sales_channel_api %></td>
    <td><%= link_to 'Edit', edit_sales_channel_api_path(sales_channel_api) %></td>
    <td><%= link_to 'Destroy', sales_channel_api, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sales channel api', new_sales_channel_sales_channel_api_path %>
<%= link_to 'Back', sales_channels_path %>

app/views/sales_channel_apis/new.html.erb
<h1>New sales_channel_api</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_channel_sales_channel_apis_path(@sales_channel) %>

app/views/sales_channel_apis/show.html.erb
<p>
  <b>Name:</b>
  <%= @sales_channel_api.name %>
</p>

<p>
  <b>App key:</b>
  <%= @sales_channel_api.app_key %>
</p>

<p>
  <b>App secret:</b>
  <%= @sales_channel_api.app_secret %>
</p>

<p>
  <b>Session key:</b>
  <%= @sales_channel_api.session_key %>
</p>

<p>
  <b>Url:</b>
  <%= @sales_channel_api.url %>
</p>

<p>
  <b>Is enable:</b>
  <%= @sales_channel_api.is_enable %>
</p>

<%= link_to 'Edit', edit_sales_channel_api_path(@sales_channel_api) %> |
<%= link_to 'Back', sales_channel_sales_channel_apis_path(@sales_channel_api.sales_channel) %>