config/routes.rb
ReportCenter::Application.routes.draw do

  get "home/index"
  root :to => "home#index"

  resources :activities

  resources :products do
    collection do
      get :search
    end
  end

  resources :orders

  resources :sales_channels do
    resources :sales_channel_apis
  end

  resources :sales_channel_apis

  resources :product_outer_mappings

  devise_for :users

end

app/models/product_outer_mapping.rb
class ProductOuterMapping < ActiveRecord::Base
  validates :outer_sku, :presence => true, :length => { :maximum => 255 }

  belongs_to :product
  belongs_to :sales_channel_api

  validates :product, :presence => true
  validates :sales_channel_api, :presence => true
end

app/controllers/product_outer_mappings_controller.rb
class ProductOuterMappingsController < ApplicationController
  before_filter :authenticate_user!
  # GET /product_outer_mappings
  # GET /product_outer_mappings.json
  def index
    @product_outer_mappings = ProductOuterMapping.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @product_outer_mappings }
    end
  end

  # GET /product_outer_mappings/1
  # GET /product_outer_mappings/1.json
  def show
    @product_outer_mapping = ProductOuterMapping.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product_outer_mapping }
    end
  end

  # GET /product_outer_mappings/new
  # GET /product_outer_mappings/new.json
  def new
    @product_outer_mapping = ProductOuterMapping.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product_outer_mapping }
    end
  end

  # GET /product_outer_mappings/1/edit
  def edit
    @product_outer_mapping = ProductOuterMapping.find(params[:id])
  end

  # POST /product_outer_mappings
  # POST /product_outer_mappings.json
  def create
    @product_outer_mapping = ProductOuterMapping.new(params[:product_outer_mapping])

    respond_to do |format|
      if @product_outer_mapping.save
        format.html { redirect_to @product_outer_mapping, :notice => 'Product outer mapping was successfully created.' }
        format.json { render :json => @product_outer_mapping, :status => :created, :location => @product_outer_mapping }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product_outer_mapping.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /product_outer_mappings/1
  # PUT /product_outer_mappings/1.json
  def update
    @product_outer_mapping = ProductOuterMapping.find(params[:id])

    respond_to do |format|
      if @product_outer_mapping.update_attributes(params[:product_outer_mapping])
        format.html { redirect_to @product_outer_mapping, :notice => 'Product outer mapping was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product_outer_mapping.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /product_outer_mappings/1
  # DELETE /product_outer_mappings/1.json
  def destroy
    @product_outer_mapping = ProductOuterMapping.find(params[:id])
    @product_outer_mapping.destroy

    respond_to do |format|
      format.html { redirect_to product_outer_mappings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/product_outer_mappings_helper.rb
module ProductOuterMappingsHelper
end

app/views/product_outer_mappings/_form.html.erb
<%= form_for(@product_outer_mapping) do |f| %>
  <% if @product_outer_mapping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_outer_mapping.errors.count, "error") %> prohibited this product_outer_mapping from being saved:</h2>

      <ul>
      <% @product_outer_mapping.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :outer_sku %>
    <%= f.text_field :outer_sku %>
  </div>

  <div>
    <%= render :partial => "sales_channel_apis/widget_api_select", :locals => { :form => f } %>
  </div>
  <div class="add-product">
    <%= render :partial => "products/widget_selectable_list", :locals => { :form => f } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_outer_mappings/edit.html.erb
<h1>Editing product_outer_mapping</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_outer_mapping %> |
<%= link_to 'Back', product_outer_mappings_path %>

app/views/product_outer_mappings/index.html.erb
<h1>Listing product_outer_mappings</h1>

<table>
  <tr>
    <th>outer sku</th>
    <th>app key</th>
    <th>sales channel</th>
    <th>product sku</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_outer_mappings.each do |product_outer_mapping| %>
  <tr>
    <td><%= product_outer_mapping.outer_sku %></td>
    <% if product_outer_mapping.sales_channel_api.nil? %>
    <td></td>
    <td></td>
    <% else %>
    <td><%= product_outer_mapping.sales_channel_api.app_key %></td>
    <td><%= product_outer_mapping.sales_channel_api.sales_channel.name if not product_outer_mapping.sales_channel_api.sales_channel.nil? %></td>
    <% end %>
    <td><%= product_outer_mapping.product.sku if not product_outer_mapping.product.nil? %></td>
    <td><%= link_to 'Show', product_outer_mapping %></td>
    <td><%= link_to 'Edit', edit_product_outer_mapping_path(product_outer_mapping) %></td>
    <td><%= link_to 'Destroy', product_outer_mapping, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product outer mapping', new_product_outer_mapping_path %>

app/views/product_outer_mappings/new.html.erb
<h1>New product_outer_mapping</h1>

<%= render 'form' %>

<%= link_to 'Back', product_outer_mappings_path %>

app/views/product_outer_mappings/show.html.erb
<p>
  <b>Name:</b>
  <%= @product_outer_mapping.product.name if not @product_outer_mapping.product.nil? %>
</p>

<p>
  <b>Outer Sku:</b>
  <%= @product_outer_mapping.outer_sku %>
</p>

<p>
  <b>Inner Sku:</b>
  <%= @product_outer_mapping.product.sku if not @product_outer_mapping.product.nil?%>
</p>

<p>
  <b>Sales Channel</b>
  <%= @product_outer_mapping.sales_channel_api.sales_channel.name if not @product_outer_mapping.sales_channel_api.nil? %>
</p>

<p>
  <b>Sales Channel Api</b>
  <%= @product_outer_mapping.sales_channel_api.name if not @product_outer_mapping.sales_channel_api.nil? %>
</p>

<%= link_to 'Edit', edit_product_outer_mapping_path(@product_outer_mapping) %> |
<%= link_to 'Back', product_outer_mappings_path %>