config/routes.rb
ReportCenter::Application.routes.draw do

  get "home/index"
  root :to => "home#index"

  resources :activities

  resources :products do
    collection do
      get :search
    end
  end

  resources :orders

  resources :sales_channels do
    resources :sales_channel_apis
  end

  resources :sales_channel_apis

  resources :product_outer_mappings

  devise_for :users

end

app/models/sales_channel.rb
class SalesChannel < ActiveRecord::Base
  validates :name, :presence => true, :length => 2..30
  validates :code, :presence => true, :length => 2..30

  validates :comment, :presence => true, :length => { :maximum => 255 }
  has_many :apis, :class_name => "SalesChannelApi", :dependent => :destroy
end

app/controllers/sales_channels_controller.rb
class SalesChannelsController < ApplicationController
  before_filter :authenticate_user!

  # GET /sales_channels
  # GET /sales_channels.json
  def index
    @sales_channels = SalesChannel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @sales_channels }
    end
  end

  # GET /sales_channels/1
  # GET /sales_channels/1.json
  def show
    @sales_channel = SalesChannel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @sales_channel }
    end
  end

  # GET /sales_channels/new
  # GET /sales_channels/new.json
  def new
    @sales_channel = SalesChannel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @sales_channel }
    end
  end

  # GET /sales_channels/1/edit
  def edit
    @sales_channel = SalesChannel.find(params[:id])
  end

  # POST /sales_channels
  # POST /sales_channels.json
  def create
    @sales_channel = SalesChannel.new(params[:sales_channel])

    respond_to do |format|
      if @sales_channel.save
        format.html { redirect_to @sales_channel, :notice => 'Sales channel was successfully created.' }
        format.json { render :json => @sales_channel, :status => :created, :location => @sales_channel }
      else
        format.html { render :action => "new" }
        format.json { render :json => @sales_channel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sales_channels/1
  # PUT /sales_channels/1.json
  def update
    @sales_channel = SalesChannel.find(params[:id])

    respond_to do |format|
      if @sales_channel.update_attributes(params[:sales_channel])
        format.html { redirect_to @sales_channel, :notice => 'Sales channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @sales_channel.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_channels/1
  # DELETE /sales_channels/1.json
  def destroy
    @sales_channel = SalesChannel.find(params[:id])
    @sales_channel.destroy

    respond_to do |format|
      format.html { redirect_to sales_channels_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/sales_channels_helper.rb
module SalesChannelsHelper
end

app/views/sales_channels/_form.html.erb
<%= form_for(@sales_channel) do |f| %>
  <% if @sales_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_channel.errors.count, "error") %> prohibited this sales_channel from being saved:</h2>

      <ul>
      <% @sales_channel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales_channels/edit.html.erb
<h1>Editing sales_channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_channel %> |
<%= link_to 'Back', sales_channels_path %>

app/views/sales_channels/index.html.erb
<h1>Listing sales_channels</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sales_channels.each do |sales_channel| %>
  <tr>
    <td><%= sales_channel.name %></td>
    <td><%= sales_channel.code %></td>
    <td><%= sales_channel.comment %></td>
    <td><%= link_to 'Show', sales_channel %></td>
    <td><%= link_to 'Edit', edit_sales_channel_path(sales_channel) %></td>
    <td><%= link_to 'Destroy', sales_channel, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'Add Api', new_sales_channel_sales_channel_api_path(sales_channel) %></td>
    <td><%= link_to 'List Api', sales_channel_sales_channel_apis_path(sales_channel) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sales channel', new_sales_channel_path %>

app/views/sales_channels/new.html.erb
<h1>New sales_channel</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_channels_path %>

app/views/sales_channels/show.html.erb
<p>
  <b>Name:</b>
  <%= @sales_channel.name %>
</p>

<p>
  <b>Code:</b>
  <%= @sales_channel.code %>
</p>

<p>
  <b>Comment:</b>
  <%= @sales_channel.comment %>
</p>


<%= link_to 'Edit', edit_sales_channel_path(@sales_channel) %> |
<%= link_to 'Back', sales_channels_path %>